server:
  host: localhost
  port: 9020

db:
  name: db.sqlite
  migrations:
    path: internal/db/migrations

ai:
  models:
    embeddings: text-embedding-004
    generative: gemini-2.5-flash
  relevant_topics:
    scope:
      - scope 1
      - scope 2
      - scope 3
    net-zero: 
      - net-zero
      - net zero
      - net-zero target
      - net zero target

adapter:
  # supported adapters
  # 1. pdf (extracts text from PDF locally using code)
  # 2. document (uses Gemini document vision)
  extract: pdf
