http:
  port: 8080

db:
  name: db.sqlite
  opts: _fk=true&_journal=WAL&_timeout=5000

weaviate:
  addr: localhost:9035

redis:
  addr: localhost:6379
  password: ""
  db: 0 # use default DB
  protocol: 2
  index: ragserver-idx
  index_prefix: "doc:"
  vector_dim: 768 # 768 for text-embedding-004, 384 for all-MiniLM-L6-v2
  vector_distance_metric: L2

relevant_topics:
  scope:
    - scope 1
    - scope 2
    - scope 3
  net-zero: 
    - net-zero
    - net zero
    - net-zero target
    - net zero target

hugot:
  # Supported backends:
  # 1. go
  # 2. ort
  backend: go
  nnxruntime_path: /usr/lib64/onnxruntime.so
  models_dir: /models

adapter:
  # Supported adapters for extracting text from PDFs:
  # 1. pdf (extracts text from PDF locally using code)
  # 2. document (uses Gemini document vision)
  extract: 
    name: pdf
    model: gemini-2.5-flash # only used if name is document
  # Supported models for generating embeddings:
  # 1. google-genai
  # 2. hugot
  embed: 
    name: google-genai # google-genai or hugot
    model: text-embedding-004 # text-embedding-004 or all-MiniLM-L6-v2
  # Supported models for storing and retrieving embeddings:
  # 1. weaviate
  # 2. redis
  retrieve: 
    name: redis
  # Supported models for generating text:
  # 1. google-genai
  # 2. hugot
  generative:
    name: google-genai
    model: gemini-2.5-flash
    # name: hugot
    # model: onnx-community/gemma-3-270m-it-ONNX
    # external_data_path: onnx/model.onnx_data