http:
  port: 8080

db:
  host: localhost
  port: 5432
  user: "ragserver"
  password: "ragserver"
  name: "ragserver"
  sslmode: disable

redis:
  addr: localhost:6379
  password: ""
  db: 0
  protocol: 2
  index: ragserver-idx
  index_prefix: "doc:"
  vector_dim: 768
  vector_distance_metric: L2

relevant_topics:
  scope:
    - scope 1
    - scope 2
    - scope 3
  net-zero: 
    - net-zero
    - net zero
    - net-zero target
    - net zero target

hugot:
  backend: go
  onnxruntime_path: /usr/lib64/onnxruntime.so
  models_dir: ./models

adapter:
  filestorage:
    dir: ./files
  extract: 
    name: pdf
    #model: gemini-2.5-flash
  embed: 
    name: hugot
    model: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
    onx_file_path: onnx/model.onnx
    # name: google-genai
    # model: text-embedding-004
  retrieve: 
    name: redis
  generative: 
    name: hugot
    model: onnx-community/gemma-3-1b-it-ONNX-GQA
    onx_file_path: onnx/model.onnx
    templates_dir: templates/hugot/
    external_data_path: onnx/model.onnx_data
