http:
  host: localhost
  port: 9020

db:
  name: db.sqlite

redis:
  addr: localhost:6379
  password: ""
  db: 0
  protocol: 2
  index: ragserver-idx
  index_prefix: "doc:"
  vector_dim: 384
  vector_distance_metric: L2

relevant_topics:
  scope:
    - scope 1
    - scope 2
    - scope 3
  net-zero: 
    - net-zero
    - net zero
    - net-zero target
    - net zero target

adapter:
  extract: 
    name: pdf
    model: gemini-2.5-flash
  embed: 
    name: hugot
    model: all-MiniLM-L6-v2
  retrieve: 
    name: redis
  generative: 
    model: gemini-2.5-flash
