http:
  port: 8080

db:
  name: db.sqlite
  opts: _fk=true&_journal=WAL&_timeout=5000

weaviate:
  addr: localhost:9035

relevant_topics:
  scope:
    - scope 1
    - scope 2
    - scope 3
  net-zero: 
    - net-zero
    - net zero
    - net-zero target
    - net zero target

adapter:
  extract: 
    name: pdf
    model: gemini-2.5-flash
  embed: 
    name: google-genai
    model: text-embedding-004
  generative: 
    name: google-genai
    model: gemini-2.5-flash
