http:
  port: 8080

db:
  host: localhost
  port: 5432
  user: "ragserver"
  password: "ragserver"
  name: "ragserver"
  sslmode: disable

weaviate:
  addr: localhost:9035

relevant_topics:
  scope:
    - scope 1
    - scope 2
    - scope 3
  net-zero: 
    - net-zero
    - net zero
    - net-zero target
    - net zero target

# hugot:
#   # Supported backends:
#   # 1. go
#   # 2. ort
#   backend: ort
#   nnxruntime_path: /usr/lib64/onnxruntime.so
#   models_dir: /models

adapter:
  filestorage:
    dir: ./files
  extract: 
    name: pdf
    #model: gemini-2.5-flash
  embed: 
    name: google-genai
    model: text-embedding-004
  generative: 
    name: google-genai
    model: gemini-2.5-flash
    templates_dir: templates/google-genai
